# Read the Docs configuration file for Sphinx projects
version: 2

# Set the OS and Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.11.7"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Install Python dependencies from requirements.txt
python:
  install:
    - requirements: docs/requirements.txt  # Path to your requirements file