version: 2

# Build documentation using Sphinx
sphinx:
  configuration: docs/conf.py  # Path to your Sphinx configuration file

# Define the Python version and install dependencies
python:
  version: 3.11  # Specify the Python version

  # Install necessary dependencies for building the documentation
  install:
    - requirements: docs/requirements.txt  # If you use a requirements.txt file

# Alternatively, you can define the packages directly
  extra_requirements:
    - sphinx
    - furo  # Replace with the theme you're using, like 'alabaster', 'readthedocs', etc.
    - numpy
    - pandas
    - scipy
    - plotly
    - sphinx-copybutton

# Customize the build command (optional if you need specific steps)
build:
  commands:
    - sphinx-build -b html docs docs/_build/html  # Adjust paths if necessary
