name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main  # or master if your default branch is master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # specify your Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install furo  # or sphinx_rtd_theme, or another theme you are using
        pip install Pygments
        pip install -r requirements.txt

    - name: Build the documentation
      run: |
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
